### ISSUE TITLE
fatal error quand on veut prévisualiser un thème côté admin alors qu'il est sélectionné côté public

### ISSUE THREAD

**Issue by brol** [JcDenis/arlequin#2]
coucou
dc 2.28-dev-r20230814.0320 - php 8.1 - arlequin 2.3
tu me diras que c'est probablement normal mais le message fait peur, bouh !
manip pour avoir le message qui fout la trouille :
admin, choix du thème blowup.
public, choix du thème chestnut avec le plugin arlequin.
admin je clique sur chestnut et je prévisualise (je sais c'est débile puisque j'ai déjà l'affichage côté public mais bon), et zou, message d'erreur : 
`<font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Cannot redeclare chestnutPublicHeadContent() (previously declared in F:\wamp64\www\labodc2\lab\themes\chestnut\_public.php:27) in F:\wamp64\www\labodc2\lab\themes\chestnut\_public.php on line <i>27</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>364328</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='F:\wamp64\www\labodc2\lab\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0003</td><td bgcolor='#eeeeec' align='right'>364736</td><td bgcolor='#eeeeec'>require( <font color='#00bb00'>'F:\wamp64\www\labodc2\dotclear\inc\public\prepend.php</font> )</td><td title='F:\wamp64\www\labodc2\lab\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>3</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0004</td><td bgcolor='#eeeeec' align='right'>364736</td><td bgcolor='#eeeeec'>Dotclear\App::bootstrap( <span>$utility = </span><span>&#39;Frontend&#39;</span>, <span>$process = </span>??? )</td><td title='F:\wamp64\www\labodc2\dotclear\inc\public\prepend.php' bgcolor='#eeeeec'>...\prepend.php<b>:</b>15</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0046</td><td bgcolor='#eeeeec' align='right'>494576</td><td bgcolor='#eeeeec'>Dotclear\App::utility( <span>$utility = </span><span>&#39;Dotclear\\Core\\Frontend\\Utility&#39;</span>, <span>$next = </span><span>TRUE</span> )</td><td title='F:\wamp64\www\labodc2\dotclear\src\App.php' bgcolor='#eeeeec'>...\App.php<b>:</b>69</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.0046</td><td bgcolor='#eeeeec' align='right'>494576</td><td bgcolor='#eeeeec'>Dotclear\Core\Frontend\Utility::process(  )</td><td title='F:\wamp64\www\labodc2\dotclear\src\App.php' bgcolor='#eeeeec'>...\App.php<b>:</b>596</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.1235</td><td bgcolor='#eeeeec' align='right'>1601800</td><td bgcolor='#eeeeec'>dcUrlHandlers->getDocument(  )</td><td title='F:\wamp64\www\labodc2\dotclear\src\Core\Frontend\Utility.php' bgcolor='#eeeeec'>...\Utility.php<b>:</b>299</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.1236</td><td bgcolor='#eeeeec' align='right'>1604688</td><td bgcolor='#eeeeec'>Dotclear\Helper\Network\UrlHandler->callHandler( <span>$type = </span><span>&#39;try&#39;</span>, <span>$args = </span><span>&#39;admin/86608317128af50561936ff4f16f3f371442cb0f/chestnut&#39;</span> )</td><td title='F:\wamp64\www\labodc2\dotclear\inc\public\lib.urlhandlers.php' bgcolor='#eeeeec'>...\lib.urlhandlers.php<b>:</b>249</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.1236</td><td bgcolor='#eeeeec' align='right'>1604688</td><td bgcolor='#eeeeec'>Dotclear\Helper\Network\UrlHandler->callHelper( <span>$handler = </span><span>[0 =&gt; &#39;dcUrlHandlers&#39;, 1 =&gt; &#39;try&#39;]</span>, <span>$args = </span><span>&#39;admin/86608317128af50561936ff4f16f3f371442cb0f/chestnut&#39;</span>, <span>$type = </span><span>&#39;try&#39;</span> )</td><td title='F:\wamp64\www\labodc2\dotclear\src\Helper\Network\UrlHandler.php' bgcolor='#eeeeec'>...\UrlHandler.php<b>:</b>263</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.1236</td><td bgcolor='#eeeeec' align='right'>1604688</td><td bgcolor='#eeeeec'><a href='[http://www.php.net/function.call-user-func:{F:\wamp64\www\labodc2\dotclear\src\Helper\Network\UrlHandler.php:237}](view-source:http://www.php.net/function.call-user-func:%7BF:/wamp64/www/labodc2/dotclear/src/Helper/Network/UrlHandler.php:237%7D)' target='_new'>call_user_func:{F:\wamp64\www\labodc2\dotclear\src\Helper\Network\UrlHandler.php:237}</a>( <span>$callback = </span><span>[0 =&gt; &#39;dcUrlHandlers&#39;, 1 =&gt; &#39;try&#39;]</span>, <span>$args = </span><span>&#39;admin/86608317128af50561936ff4f16f3f371442cb0f/chestnut&#39;</span> )</td><td title='F:\wamp64\www\labodc2\dotclear\src\Helper\Network\UrlHandler.php' bgcolor='#eeeeec'>...\UrlHandler.php<b>:</b>237</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.1236</td><td bgcolor='#eeeeec' align='right'>1604760</td><td bgcolor='#eeeeec'>dcUrlHandlers::try( <span>$args = </span><span>&#39;admin/86608317128af50561936ff4f16f3f371442cb0f/chestnut&#39;</span> )</td><td title='F:\wamp64\www\labodc2\dotclear\src\Helper\Network\UrlHandler.php' bgcolor='#eeeeec'>...\UrlHandler.php<b>:</b>237</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.1257</td><td bgcolor='#eeeeec' align='right'>1653696</td><td bgcolor='#eeeeec'>dcThemes->loadNsFile( <span>$id = </span><span>&#39;chestnut&#39;</span>, <span>$ns = </span><span>&#39;public&#39;</span> )</td><td title='F:\wamp64\www\labodc2\dotclear\inc\public\lib.urlhandlers.php' bgcolor='#eeeeec'>...\lib.urlhandlers.php<b>:</b>690</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.1261</td><td bgcolor='#eeeeec' align='right'>1653952</td><td bgcolor='#eeeeec'>dcModules->loadModuleFile( <span>$________ = </span><span>&#39;F:\\wamp64\\www\\labodc2\\dotclear/../lab/themes\\chestnut\\_public.php&#39;</span>, <span>$globals = </span><span>TRUE</span>, <span>$catch = </span>??? )</td><td title='F:\wamp64\www\labodc2\dotclear\inc\core\class.dc.themes.php' bgcolor='#eeeeec'>...\class.dc.themes.php<b>:</b>237</td></tr>
</table></font>`

**Comment by JcDenis** [comment]
Joli celui-là, et je comprend qu'il n'aime pas, par contre j'ai aucune idée de comment je vais le corriger 😅

**Comment by brol** [comment]
en l'occurrence, c'est chestnut qui était sélectionné côté public avec arlequin (je corrige mon premier message).

**Comment by JcDenis** [comment]
Normalement corrigé avec la version arlequin 2.4
